### ISSUE TITLE
Add online FMU Check

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard.org#275]
I've created a new [prototype of the online FMU Check](https://fmu-check.herokuapp.com/).

@TorstenBlochwitz, @chrbertsch, @andreas-junghanns, please add your feedback and suggestions here, so we can improve it and vote on releasing it at the next steering committee meeting.

The source code will be released on GitHub when we go live.

**Comment by fajansen** [comment]
Display of Parameters and Ports would be nice

**Comment by andreas-junghanns** [comment]
I tested a few FMUs, most passed.
I like the simplicity of use.
Speed is great.

Some old ones had names that caused errors:
{{{
"clutch1.mue_pos[1, 1]" (line 377) is not a legal variable name for naming convention "structured". No terminal defined for ' ' at line 1 col 19 clutch1.mue_pos[1, 1] ^ Expecting: {'__ANON_3'} 
}}}
Apparently, the space is blamed (the location saved the day), but the error message as such is kind of cryptic.

Of course it would be nice to list also, what is NOT tested. At least in general terms. (run-time properties, ...)

**Comment by t-sommer** [comment]
> Of course it would be nice to list also, what is NOT tested. At least in general terms. (run-time properties, ...)

Can you please propose a list?

**Comment by chrbertsch** [comment]
For defect FMUs (non fmu-ending, non zip-files, corrupt zip files) the Website hangs. I will send you an example of such a corrup FMU via email

**Comment by chrbertsch** [comment]
Currently this is a static check only. 
It would be great to add a test of instantiation and simulation of the FMU also (similar as with the FMU Compliance Checker). Perhaps this could even be combined with displaying results via the new fmpy Web app.

As this checker is based on fmpy, it would be good to document this (and link to the sources), so that people can inspect it.

**Comment by andreas-junghanns** [comment]
> 
> 
> Currently this is a static check only.
> It would be great to add a test of instantiation and simulation of the FMU also (similar as with the FMU Compliance Checker). Perhaps this could even be combined with displaying results via the new fmpy Web app.
> 
> As this checker is based on fmpy, it would be good to document this (and link to the sources), so that people can inspect it.

What would you do for the different platforms supported in one FMU?

**Comment by t-sommer** [comment]
> What would you do for the different platforms supported in one FMU?

Currently the web app runs on a x86_64 Linux host. We could extend it to a more complex setup with additional Windows and Mac workers. Maybe even use use [Wine](https://www.winehq.org/)?

**Comment by t-sommer** [comment]
> For defect FMUs (non fmu-ending, non zip-files, corrupt zip files) the Website hangs. I will send you an example of such a corrup FMU via email

- [X] fixed

**Comment by TorstenBlochwitz** [comment]
I tested some FMUs and it worked very well. 

The description looks good to me. I would propose something like:
This FMU check does not compute (or execute, or run) the the FMU! If you want to do so, please use <link to FMU Compliance Checker> or <link to FMPy>.

In addition to that: I assume the FMU is uploaded to somewhere. If it is like this, we should inform potential users about it, because this might be against data protection rules. 
I would propose to add something like this directly under the heading: Please note: The FMU-file is uploaded to the server ... The FMU Check tool deletes all stored data after the checking. However it might happen that some data stay there by accident. Please check if this procedure is compliant to your data protection rules for your FMU!

Is there any usage information stored (IP Adress, FMU name, test result, time...)? We should add a statement about that too.

**Comment by ishengyeh** [comment]
Hi, many thanks forthis great tool, so easy to use.  Here I got a FMU which failed to pass your test; however, it passed FMUChecker_2.0.4 from fmi-standard.  The error message from your app is: ModelStructure/Outputs must have exactly one entry for each variable with causality="output".  Could you please kindly let me know what is causing this complaint?  Thanks a lot.

**Comment by t-sommer** [comment]
The `modelDescription.xml` of your FMU does not have the required entries in `ModelStructure/Outputs` (see [FMI 2.0.3 Spec](https://github.com/modelica/fmi-standard/releases/download/v2.0.3/FMI-Specification-2.0.3.pdf), p. 61).

**Comment by ishengyeh** [comment]
Thanks a lot for the response.  I took a 2nd look at my xml and failed to see anything wrong for OUTPUT variable description, Could you please take a look at my xml file and tell me exactly what is wrong with it?  Your help is highly appreciated. my fmu file: 
[INV_PEND3.zip](https://github.com/modelica/fmi-standard.org/files/7694883/INV_PEND3.zip)
u

**Comment by t-sommer** [comment]
The FMU has one output variable `FX621`

```xml
  <ScalarVariable name="FX621" valueReference="0" description=" "
                  causality="output" variability="continuous" initial="exact">
    <Real start="0"/>
  </ScalarVariable>
```

but no corresponding entry in `ModelStructure/Outputs`

```xml
</ModelVariables>
<ModelStructure>
```

See https://github.com/modelica/Reference-FMUs/blob/master/BouncingBall/FMI2.xml for a valid example of an FMU with outputs.

**Comment by ishengyeh** [comment]
Thanks a lot, it works now.  Highly appreciate your help.

**Comment by ishengyeh** [comment]
Sorry to bother you again, here I have a FMU passing your compliance checker; however it crashed in the checker of FMUChecker-2.0.4-linux64 downloaded from https://github.com/modelica-tools/FMUComplianceChecker/releases.  It just crashed w/o any message, see below.  I tried to follow BUILD.md to build the checker so that I can debug by myself, I run into some error message, also attached.  Could I have your comment? thanks. a lot.
--- ERROR from downloaded compliance checker ---
/net/nas2/nas2_1/isheng/fmu/FMUChecker-2.0.4-linux64/fmuCheck.linux64 INV_PEND1.fmu
[INFO][FMUCHK] Will process FMU INV_PEND1.fmu
[INFO][FMILIB] XML specifies FMI standard version 2.0
[INFO][FMUCHK] Model name: INV_PEND1
[INFO][FMUCHK] Model GUID: {t8jhfhkm-bo5o-4wys-29ip-0005ttfss4fd}
[INFO][FMUCHK] Model version: 
[INFO][FMUCHK] FMU kind: CoSimulation
[INFO][FMUCHK] The FMU contains:
...........
[INFO][FMUCHK] No input data provided. In case of simulation initial values from FMU will be used.
[INFO][FMUCHK] Printing output file header
"time","DX500","VX500","DX608","VX608"
[INFO][FMUCHK] Model identifier for CoSimulation: INV_PEND1
[INFO][FMILIB] Loading 'linux64' binary with 'default' platform types
[INFO][FMUCHK] Version returned from CS FMU:   2.0
Segmentation fault (core dumped)
[INV_PEND1(1).zip](https://github.com/modelica/fmi-standard.org/files/7705844/INV_PEND1.1.zip)
--------------------------ERROR from installing the checker following BUILD.md ------------------------------------
cmake -DFMUCHK_INSTALL_PREFIX=../install   /data1/isheng/fmu/FMUComplianceChecker-2.0.4
CMake Warning (dev) at CMakeLists.txt:151:
  Syntax Warning in cmake code at column 85
-- FMIL version: Test
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:157 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in   <---- error message when cmake
  add_dependencies
  The dependency target
  "/data1/isheng/fmu/FMUComplianceChecker-2.0.4/CMakeLists.txt" of target
  "fmil" does not exist.                                                                       <---- error message when cmake
CMake Warning (dev) at CMakeLists.txt:157 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
The dependency target
  "/data1/isheng/fmu/FMUComplianceChecker-2.0.4/build/CMakeCache.txt" of
  target "fmil" does not exist.                                                               <---- error message when cmake
-- Generating done
-- Build files have been written to: /data1/isheng/fmu/FMUComplianceChecker-2.0.4/build
FMUComplianceChecker-2.0.4/build% make install test
Scanning dependencies of target fmil
[  5%] Creating directories for 'fmil'
[ 10%] Performing download step (SVN checkout) for 'fmil'
svn: E170013: Unable to connect to a repository at URL 'https://svn.jmodelica.org/FMILibrary/tags/2.0.3'
svn: E230001: Server SSL certificate verification failed: certificate issued for a different hostname
make[2]: *** [CMakeFiles/fmil.dir/build.make:109: FMIL/src/fmil-stamp/fmil-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/fmil.dir/all] Error 2
make: *** [Makefile:158: all] Error 2

**Comment by t-sommer** [comment]
Please open an issue on https://github.com/modelica-tools/FMUComplianceChecker/issues.

**Comment by ishengyeh** [comment]
Just opened, thanks.
