### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by xogeny** [modelica/fmi-standard.org#29]
@andreas-junghanns asked about tracking visitors here.

@andreas-junghanns, please confirm you want to add this...

**Comment by andreas-junghanns** [comment]
Yes, please add.

**Comment by MartinOtter** [comment]
It must be added in such a form, that no personal data is used, in order to fulfill the new EU regulations GDPR (see e.g. https://blog.convert.com/google-analytics-and-gdpr-is-it-compliant.html)

**Comment by GallLeo** [comment]
Doesn't this add the inconvenience for all visitors to click away the "We are using Cookies" pop-up?

**Comment by xogeny** [comment]
Actually, this should be done by the web masters.  It is going to involve potentially multiple sites and it should be done in a consistent way.  Furthermore, the analytics should be collected under the MA webmaster account (which I don't seem to have access to at the moment).

I did find [a nice link about GDPR](https://medium.com/@subsign/google-analytics-and-gdpr-compliance-3fad792babf5) though.

**Comment by xogeny** [comment]
@GallLeo As far as I know, Google Analytics doesn't pop up any such dialog.  Do you know otherwise?  I say this because I use it on multiple sites and *I've* never seen such a popup.

**Comment by dietmarw** [comment]
The behaviour of **not** showing the pop-up is probably a violation of the European rules itself. IIRC then when ever a site uses cookies it needs to inform the visitor about this in such a way that the visitor need to acknowledge this.

**Comment by xogeny** [comment]
Or perhaps it just doesn’t use cookies.  I really have no idea.  But I assume Google would do what is necessary to comply...

**Comment by GallLeo** [comment]
Maybe you don't need it, because you are located in U.S.?

There is nearly no bigger website anymore, which doesn't have these nasty pop-ups.
I asked a friend, who runs a web development business. According to him, you do need the "Cookie Law Pop-up" for Google Analytics. They use a payed service www.iubenda.com in order to generate these texts based on the used services.

**Comment by sjoelund** [comment]
You not only need the user to consent; you need to store when the user consented to this tracking. Perhaps storing a time-stamp in the cookie plus which version of the consent would suffice; I am not sure. Note that you need a way to remove consent which is as easy or easier than giving consent; in most web browsers clearing the cookies for a web page is cumbersome so ideally you should then have a button to clear cookies?

You need consent for permanent cookies, session cookies, etc containing any personal information. Which is problematic because Trac and Plone uses session cookies and are not GDPR-compliant (and they by default store a session, which is a no-no). We also couldn't simply add some JavaScript to the webpage to popup some consent box because the webpage would already have added a session cookie in the HTTP response as far as I can tell.

The best solution that is fully GDPR-compliant seems to be: don't perform any tracking, shut down the Trac and Plone systems, disable Apache logging and serve only HTML unless we have a better solution...

The only solution I can see would be to have our systems using server-side scripting (session cookies, etc):
* Implement a server-side check for a cookie in all the languages used (Plone would be annoying to change)
For systems not using server-side scripting:
* Only load external JavaScript such as Google analytics if consent has been given (cookie is set)

The link given by @GallLeo suggests turning on IP anonymization in Google Analytics, but all this does is zero out the last octet in the IP which basically does nothing and I would not use it without consent to be on the safe side. It should be turned on even if consent is given...

@MartinOtter added in notifications since this concerns also other MA webpages.

With all this in mind: do you really want to make the fmi-standard.org homepage popup a dialog asking for consent to track the user via Google Analytics (that the user has to tick manually)? (There is not anything useful that you would like to perform, right?)

**Comment by GallLeo** [comment]
@t-sommer How is an e-mail form related to Google Analytics?

Personally, I don't like these pop-ups at all. 
Why adding annoyance to many users, what would you use the usage data for?

We should check carefully, if consent is required. If we don't need active consent, then we should be good to go? (given we add it to the privacy statement, in a proper way).
"It would also seem that if you are NOT using advertising features with Google Analytics, then you do not need consent (more advice on that further below)."
Source: https://www.blastam.com/blog/gdpr-need-consent-for-google-analytics-tracking

So, for me, the situation regarding Google Analytics is still unclear. Does somebody have input?

**Comment by sjoelund** [comment]
@GallLeo the link you provided states:
> You should strongly consider gaining consent in the following situations:
> * Collection of a User ID.
> * Collection of any other pseudonymous identifiers.
> * Collection of detailed geographic data (postal code, latitude/longitude coordinates).

IP addresses should qualify. Any sort of tracking does as well (an identifier is created for this). Just don't use Google analytics and save us a lot of headache.

At least provide a must-have use-case for tracking users.

**Comment by chrbertsch** [comment]
One could use Matomo (an open source alternative to Google Analytics, also available in a cloud-hosted form for a little fee), in a way not to process personal data, so no consent by the user would be necessary, see https://matomo.org/blog/2018/04/how-to-not-process-any-personal-data-with-matomo-and-what-it-means-for-you/

**Comment by sjoelund** [comment]
That sounds better. 2 octets masked means 16k~64k less accurate ipv4 tracking depending on sizes of IP ranges. More in line with the size of a city. The blog does not describe how ipv6 is handled though.

The problem is... it actually tries to identify individual users anyway:
> it will use a technique called Fingerprint. It is based on several metadata such as the operating system, browser, browser plugins, IP address, browser language; just to name a few  to identify a unique visitor.

**Comment by t-sommer** [comment]
@sjoelund, can you provide the API key?

**Comment by sjoelund** [comment]
I could get the key, but I won't until the page is updated to be GDPR-compliant with Google analytics default off until the user presses the button to opt in to analytics.

**Comment by sjoelund** [comment]
That code only says you use cookies with no opt-out. There needs to be a question to the user if he or she accepts being tracked, and a statement on how this data is used (which is not linked). Only after this is accepted are you allowed to load the Google analytics. To test Google analytics, you can go to https://analytics.google.com and get a code using your personal Google account.

**Comment by t-sommer** [comment]
> There needs to be a question to the user if he or she accepts being tracked, and a statement on how this data is used (which is not linked). Only after this is accepted are you allowed to load the Google analytics.

Can you cite a regulation / resource? E.g. https://www.theguardian.com/international sets the GA cookie before you accept anything. I would assume that they comply with European law.

**Comment by MartinOtter** [comment]
The issue is whether Google Analytics is used in a way so that data is anonymized before sending it to the MA web page and then it is not necessary to ask for permission (as long as MA cannot deduce which concrete visitor provided data). However, this collection of data must then be stated in the "privacy police".

I would prefer this approach if it can be implemented with reasonable effort.

Whether the guardian follows the GDPR is probably not easy to deduce because it depends on the fact whether data is anonymized. Note, according to a recent investigation https://borncity.com/win/2018/11/17/dutch-report-says-microsoft-office-is-not-gdpr-compliant/. Microsoft Word 2016 does not respect GDPR.

**Comment by t-sommer** [comment]
[Turning IP anonymization](https://support.google.com/analytics/answer/2763052?hl=en) would be totally fine for our purposes

**Comment by t-sommer** [comment]
@sjoelundl, can you please provide the JavaScript, so I can make the PR as [decided by the Steering Committee](https://github.com/modelica/fmi-design/blob/master/Meetings/2019-01-21-FMI-Steering.adoc#13-analytics-data) today?

Before we can merge the PR we need approval by @MartinOtter.

**Comment by andreas-junghanns** [comment]
@sjoelund, please help us out here soon - we are waiting to get this done so we can give the soon paying tool providers good statistics.

**Comment by sjoelund** [comment]
I don't have access to any JavaScript that makes Google Analytics GDPR-compliant. And looking at the requirements Google imposes on using their Google analytics, you would need a database to store records of the consent. I was supposed to phase out using the modelica.org server for new services, so that wouldn't work. And I don't actually administer any other systems.

See also a recent judgement against Google w.r.t. GDPR: https://www.cnil.fr/en/cnils-restricted-committee-imposes-financial-penalty-50-million-euros-against-google-llc

**Comment by t-sommer** [comment]
Wir bräuchten Zugriff auf webmaster@fmi-standard.org und den Google Account (falls er schon existiert)

Von meinem iPhone gesendet

**Comment by chrbertsch** [comment]
@GallLeo and @MartinOtter : can the backoffice clarify the legal situation regarding GDPR and suggest a solution?

**Comment by chrbertsch** [comment]
Adding a link regarding GDPR that was mentioned in the FMI Stering committee yesterday:
https://cookieconsent.insites.com/documentation/compliance/
This is really a blocker, also for the FMI Crosscheck invoicing.

**Comment by t-sommer** [comment]
Solved with 65f87a1b54c7392974c3adc1a0c6562a13bf4d35
